### ISSUE TITLE
Permission Request

### ISSUE THREAD

**Issue by rahulraman0108** [MattZ45986/Bombsquad_mods#7]
Hi @MattZ45986, I created this repository to ask you for your permission to use BombSquad's mods created by you in my github's repository for BombSquad's server files.
So, do I have your permission?

**Comment by MattZ45986** [comment]
@I-Am-The-Great, that is absolutely fine, given that credit is given where it is due.  Just make sure that my name still appears in the bottom of the screen.  (If I'm going to be handing out my mods, I at least would like my name to stay with them, if that makes sense.)  Otherwise, I'm not planning on charging money for them, so be my guest.  Free publicity in my eyes. 

However, I would like to know the name of your repository, because I cannot find it as of now.  Ultimately, I would love to see your server up and running and maybe join you for a game or two!

**Comment by rahulraman0108** [comment]
I am going to add your name to the README.md file and also on my website's page for the repository the page's link will be https://thegreat.ml/projects/7, and I am not going to do any changes in your mod's lines for bottom credit text; also though the [repository](https://github.com/I-Am-The-Great/Modded-scripts-for-BombSquad-server ) is created, it is yet empty as I am working around on the files, I will do this till the end of February, that repository will also include some new BS mods of my ideas created by me, I will also create a pull request for those mods after adding to my repository if people use them and like them; first of the ideas is a random bomb, which will have impactBlastMaterial and after explosion will give some new random effects, for example, spawning a rocket( I will use one of the upperArmModels of spazzes as according to me they resemble the rocket model most) then that rocket will follow a spaz other than the owner and after colliding, it will do a small health loss to the spaz by a hitMessage then spawn a powerup above the spaz's positon, most likely curse; 2nd idea is a soul steal bomb which after release follow a spaz then after touch to any spaz other than the owner it will continuously deplete the target's health and increase the owner's health; 3rd idea is infinity powerup (inspired by Avengers Infinity Wars) it will first take all powers of the powerup taker, then after half second it will give super punch power then 3/5 seconds after that it will give teleport powerup, then 7/10 seconds after that, it will give soul steal bomb and at last after 5 seconds it will give all normal powerups, and remove special powers; are these good ideas?

And about my server, I am only able to run that for 3 months a day, because I host that on AWS EC2 and I have yet my free tier account time that will expire in January 2020, and due to pushing every player's stats data after each round to MySQL database empties the bandwidth quota for free tier per month, and that hurts :cry: ; and I can not pay as I am yet a kid and do not earn.

And whenever my server is open, how may I inform you? Also if it is open you can connect by using scored.cf or scored.ml as IP address and 43210 port for Teams party or 43211 port for FFA party; and remember my server's IP and port is publicly available to all on my website's page, so do not think that it is private.

**Comment by Gengar-lab** [comment]
@MattZ45986 @I-Am-The-Great

Please give your discord link.

@I-Am-The-Great

Your all above ideas are good , when you will make them?

**Comment by rahulraman0108** [comment]
@Benefit-Zebra my discord id is: @TheGreat#9486
Thanks for encouraging me, and I paused making the server files in between because I started making a discord bot using python 3.7, my current planning is that first I will finish the BombSquad Official Accessories Manager  and then push it to BombSquad Official Accessory Archive, then I complete your BombSquad mods' ideas, then work on my server's files simultaneously with my discord bot.

**Comment by Gengar-lab** [comment]
@I-Am-The-Great

Can you give me direct link?I am unable to add you as a friend , its is showing :
It din't work,check spelling,number,.....

Please also give your discord server's invite code for joining if it is public.

**Comment by rahulraman0108** [comment]
https://discord.gg/kdWCnjk
